version: '3'
services:
  web:
    build: .
    ports:
      - "8000:80"
    depends_on:
      - db
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=dictionary

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=dictionary
    volumes:
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql